# Generated by Django 2.0.2 on 2018-03-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_edp_aluno',
            name='edp',
        ),
        migrations.AddField(
            model_name='db_edp_aluno',
            name='edp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.db_edp'),
        ),
    ]
