# Generated by Django 2.0.2 on 2018-03-01 22:18

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('player_audio', models.NullBooleanField()),
                ('player_imagem', models.NullBooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='anotacao_texto',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_video',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_video',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='video',
        ),
        migrations.AddField(
            model_name='recursos',
            name='edp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.db_edp'),
        ),
    ]
