# Generated by Django 2.0.2 on 2018-03-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180301_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recursos',
            new_name='db_recursos',
        ),
    ]
