# Generated by Django 2.0.3 on 2018-03-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180308_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_edp',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='db_edp',
            name='habilidades',
            field=models.ManyToManyField(to='core.db_habilidades'),
        ),
    ]
