# Generated by Django 2.0.3 on 2018-03-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180308_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_edp',
            name='video',
        ),
    ]
