# Generated by Django 2.0.3 on 2018-03-08 21:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_db_edp_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_edp',
            name='anotacao_texto',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_video',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='texto',
        ),
        migrations.AddField(
            model_name='db_edp',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
