# Generated by Django 2.0.3 on 2018-03-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180308_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_edp',
            name='anotacao_texto',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='carregar_video',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_audio',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_imagem',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='player_video',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='db_edp',
            name='video',
        ),
    ]
