# Generated by Django 2.0.3 on 2018-03-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180308_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_edp',
            name='atividades',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
